arg_bot_with_arg = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                    "team_id": "T039LJAV1",
                    "team_domain": "forter",
                    "channel_id": "D039R1N8N",
                    "channel_name": "directmes1N8L",
                    "user_name": "moshe",
                    "command": "/arg_bot",
                    "subcommand": "arg_bot",
                    "args": "moshe",
                    "text": "moshe"}

arg_bot_with_no_args = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                        "team_id": "T039LJAV1",
                        "team_domain": "forter",
                        "channel_id": "D039R1N8N",
                        "channel_name": "directmes1N8L",
                        "user_name": "moshe",
                        "command": "/arg_bot",
                        "subcommand": "arg_bot",
                        "args": "",
                        "text": ""}

no_arg_bot_without_arg = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                          "team_id": "T039LJAV1",
                          "team_domain": "forter",
                          "channel_id": "D039R1N8N",
                          "channel_name": "directmes1N8L",
                          "user_name": "moshe",
                          "command": "/no_arg_bot",
                          "subcommand": "no_arg_bot",
                          "args": "",
                          "text": ""}

no_arg_bot_with_arg = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                       "team_id": "T039LJAV1",
                       "team_domain": "forter",
                       "channel_id": "D039R1N8N",
                       "channel_name": "directmes1N8L",
                       "user_name": "moshe",
                       "command": "/no_arg_bot",
                       "subcommand": "no_arg_bot",
                       "args": "arg1",
                       "text": "arg1"}

optional_arg_bot_with_optional_arg = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                                      "team_id": "T039LJAV1",
                                      "team_domain": "forter",
                                      "channel_id": "D039R1N8N",
                                      "channel_name": "directmes1N8L",
                                      "user_name": "moshe",
                                      "command": "/optional_arg_bot",
                                      "subcommand": "optional_arg_bot",
                                      "args": "--optional=moshe",
                                      "text": "--optional=moshe"}

optional_arg_bot_with_no_arg = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                                "team_id": "T039LJAV1",
                                "team_domain": "forter",
                                "channel_id": "D039R1N8N",
                                "channel_name": "directmes1N8L",
                                "user_name": "moshe",
                                "command": "/optional_arg_bot",
                                "subcommand": "optional_arg_bot",
                                "args": "",
                                "text": ""}

two_message_bot = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                   "team_id": "T039LJAV1",
                   "team_domain": "forter",
                   "channel_id": "D039R1N8N",
                   "channel_name": "directmes1N8L",
                   "user_name": "moshe",
                   "command": "/two_message_bot",
                   "subcommand": "two_message_bot",
                   "args": "",
                   "text": ""}

help_subcommand = {"token": "07AnC3dfVot4G3sHdu0UhWsV",
                   "team_id": "T039LJAV1",
                   "team_domain": "forter",
                   "channel_id": "D039R1N8N",
                   "channel_name": "directmes1N8L",
                   "user_name": "moshe",
                   "command": "/no_arg_bot",
                   "subcommand": "no_arg_bot",
                   "args": "",
                   "text": "help"}
