arg_bot_with_arg = {"token": "slacktoken123",
                    "team_id": "team123",
                    "team_domain": "teamdomain",
                    "channel_id": "channelid",
                    "channel_name": "directmes1N8L",
                    "user_name": "derp",
                    "command": "/arg_bot",
                    "subcommand": "arg_bot",
                    "args": "derp",
                    "text": "derp"}

arg_bot_with_no_args = {"token": "slacktoken123",
                        "team_id": "team123",
                        "team_domain": "teamdomain",
                        "channel_id": "channelid",
                        "channel_name": "directmes1N8L",
                        "user_name": "derp",
                        "command": "/arg_bot",
                        "subcommand": "arg_bot",
                        "args": "",
                        "text": ""}

no_arg_bot_without_arg = {"token": "slacktoken123",
                          "team_id": "team123",
                          "team_domain": "teamdomain",
                          "channel_id": "channelid",
                          "channel_name": "directmes1N8L",
                          "user_name": "derp",
                          "command": "/no_arg_bot",
                          "subcommand": "no_arg_bot",
                          "args": "",
                          "text": ""}

no_arg_bot_with_arg = {"token": "slacktoken123",
                       "team_id": "team123",
                       "team_domain": "teamdomain",
                       "channel_id": "channelid",
                       "channel_name": "directmes1N8L",
                       "user_name": "derp",
                       "command": "/no_arg_bot",
                       "subcommand": "no_arg_bot",
                       "args": "arg1",
                       "text": "arg1"}

optional_arg_bot_with_optional_arg = {"token": "slacktoken123",
                                      "team_id": "team123",
                                      "team_domain": "teamdomain",
                                      "channel_id": "channelid",
                                      "channel_name": "directmes1N8L",
                                      "user_name": "derp",
                                      "command": "/optional_arg_bot",
                                      "subcommand": "optional_arg_bot",
                                      "args": "optional=derp",
                                      "text": "optional=derp"}

optional_arg_bot_with_no_arg = {"token": "slacktoken123",
                                "team_id": "team123",
                                "team_domain": "teamdomain",
                                "channel_id": "channelid",
                                "channel_name": "directmes1N8L",
                                "user_name": "derp",
                                "command": "/optional_arg_bot",
                                "subcommand": "optional_arg_bot",
                                "args": "",
                                "text": ""}

two_message_bot = {"token": "slacktoken123",
                   "team_id": "team123",
                   "team_domain": "teamdomain",
                   "channel_id": "channelid",
                   "channel_name": "directmes1N8L",
                   "user_name": "derp",
                   "command": "/two_message_bot",
                   "subcommand": "two_message_bot",
                   "args": "",
                   "text": ""}

help_subcommand = {"token": "slacktoken123",
                   "team_id": "team123",
                   "team_domain": "teamdomain",
                   "channel_id": "channelid",
                   "channel_name": "directmes1N8L",
                   "user_name": "derp",
                   "command": "/no_arg_bot",
                   "subcommand": "no_arg_bot",
                   "args": "",
                   "text": "help"}
